transcendence/app/static/app.js
transcendence/app/static/style.css
transcendence/app/templates/login.html
transcendence/app/templates/main.html
transcendence/app/templates/signup.html
transcendence/app/views.py

Fixed bug in login functionality.
Added loading spinner to for login page.
Styled login page.
Added cancel button to signup page.
created a navigateTo function to app.js to make it easier to navigate
added base function to register user(need development still tho!!!!!)

added signup function to app.js

---

transcendence/app/forms.py
transcendence/app/static/app.js
transcendence/app/static/router.js
transcendence/app/static/style.css
transcendence/app/templates/login.html
transcendence/app/templates/signup.html
transcendence/app/urls.py
transcendence/app/views.py

New features:
Direct navigation fixed:
- You can now directly navigate to some url.
Forms:
- Login and signup form action point to new created url(this url doesnt point to index view)
- Both login and signup should be working now.
- Added error handling and error display to user in frontend on submit form.
- Added loading spinner to signup page.

Navigation fixing

---

.dockerignore
.gitignore
Makefile
compose.yaml
transcendence/entrypoint.sh

Changes in entrypoint.sh and Makefile

Kan 23 fixing entrypoint to create admin user once

---

Makefile
transcendence/app/views.py
transcendence/entrypoint.sh
transcendence/transcendence/settings.py

Now the server realizes when a change is made in a .py file. 
Also the rule make dev was modified to update the static folder that constains the js files

Server realizes when a .py file changes

---

Makefile
compose.yaml
transcendence/app/static/js/registration.js
transcendence/app/templates/login.html
transcendence/app/templates/settings.html
transcendence/app/views.py

New things.
- Now it's possible to change the user profile through the settings. 
- The user credentials are prefilled at the moment to access settings.

Now it's possible to change the user profile

---

transcendence/app/static/js/Modal.js
transcendence/app/static/js/registration.js
transcendence/app/static/style.css
transcendence/app/templates/settings.html
transcendence/app/templates/settingsModal.html
transcendence/app/urls.py

Fixed url error on postLogin name

added modal confirmation of profile change

---

transcendence/app/static/css/signup.css
transcendence/app/static/js/dashboard.js
transcendence/app/static/js/registration.js
transcendence/app/static/router.js
transcendence/app/static/style.css
transcendence/app/templates/index.html
transcendence/app/templates/signup.html

Added logos to the signup form.

Signup added logos to coalition

---

transcendence/api/tournamentController.py
transcendence/api/urls.py
transcendence/api/views.py
transcendence/app/static/js/pongTournamentLobby.js
transcendence/app/templates/menus.html
transcendence/app/userInterface.py

New views and polished tournament.

New models

---

transcendence/api/userController.py
transcendence/app/static/app.js
transcendence/app/static/css/search.css
transcendence/app/static/js/Menus.js
transcendence/app/templates/SearchElements/friendItem.html
transcendence/app/urls.py
transcendence/app/userInterface.py
transcendence/app/views.py

Search for users and friends button output real data coming from database

Users search d bintegration

---

transcendence/app/pongTournament.py
transcendence/app/static/js/Classes/localTournamentClass.js
transcendence/app/static/js/pongTournamentCreation.js
transcendence/app/static/js/pongTournamentLobby.js
transcendence/app/templates/PongTournamentPages/newTournament.html
transcendence/app/templates/registeredPlayers.html

removed edit option from added users
removed delete button from host

Tournament updates

---

transcendence/api/api42.py
transcendence/app/static/app.js
transcendence/app/static/css/search.css
transcendence/app/static/css/set42password.css
transcendence/app/static/js/CircleChart.js
transcendence/app/static/js/set42password.js
transcendence/app/static/router.js
transcendence/app/templates/Pong1v1pages/chooseOpponent.html
transcendence/app/templates/index.html
transcendence/app/templates/login.html
transcendence/app/templates/set42password.html
transcendence/app/templates/signup.html
transcendence/app/userInterface.py

Added functionality to add the 42 password or also cancel the action
Some style changes to friends menu

Set42password

---

transcendence/app/pongTournament.py
transcendence/app/static/app.js
transcendence/app/static/css/search.css
transcendence/app/static/js/pong1v1.js
transcendence/app/static/js/pongTournamentLobby.js
transcendence/app/static/router.js
transcendence/app/templates/Pong1v1pages/chooseOpponent.html
transcendence/app/templates/Pong1v1pages/twoVtwoChooseOpponent.html

on invite players changed PIN to Pass
adapted router, to receive headers

Change pin to password

---

transcendence/api/userController.py
transcendence/app/mainPage.py
transcendence/app/pongTournament.py
transcendence/app/userInterface.py
transcendence/app/utils.py

Online status is updated regarding the events that happends in client side

Keep online status

---

transcendence/app/forms.py
transcendence/app/static/css/menus.css
transcendence/app/static/css/pong1v1.css
transcendence/app/static/css/pongPage.css
transcendence/app/static/js/friendsInvitations.js
transcendence/app/static/js/pong1v1.js
transcendence/app/static/js/pongTournamentLobby.js
transcendence/app/static/router.js
transcendence/app/templates/Pong1v1pages/endGame.html
transcendence/app/templates/menus.html

Branch has wrong name. There is only some small changes in UI and fixes

Small changes and fixes

---

transcendence/app/pongTournament.py
transcendence/app/static/css/splash.css
transcendence/app/static/js/pong1v1.js
transcendence/app/static/js/pong2v2.js
transcendence/app/templates/Pong1v1pages/OnevOne.html
transcendence/app/templates/Pong1v1pages/splash1v1.html
transcendence/app/templates/Pong1v1pages/splash2v2.html
transcendence/app/templates/Pong1v1pages/twoVtwo.html
transcendence/app/templates/Pong1v1pages/twoVtwoChooseOpponent.html
transcendence/app/templates/Pong1v1pages/twoVtwoEndGame.html
transcendence/app/templates/index.html

Added a splash page before game start, for 1v1 and 2v2 games

Splash game

---

transcendence/app/static/js/Classes/match2v2.js
transcendence/app/static/js/pong1v1.js
transcendence/app/static/js/pong2v2.js
transcendence/app/templates/Pong1v1pages/twoVtwoChooseOpponent.html
transcendence/app/templates/index.html

Matches class

---

transcendence/app/static/app.js
transcendence/app/static/js/Classes/match2v2.js
transcendence/app/static/js/pong1v1.js
transcendence/app/static/js/pong2v2.js
transcendence/app/static/js/pongTournamentLobby.js
transcendence/app/templates/Pong1v1pages/twoVtwoChooseOpponent.html

Players can be added and removed from any kind of game. Database is already integrated

Game player registration

---

Makefile
README.md
transcendence/api/tournamentController.py

more up-to-date documentation.
adding completed matches to all players involved.
before adding a player to the tournament check they are not already in the tournament.

New models documentation and modification

---

transcendence/app/static/js/localTournamentBoard.js
transcendence/app/static/js/pong1v1.js
transcendence/app/static/js/pong2v2.js
transcendence/app/static/js/pongTournamentLobby.js
transcendence/app/templates/Pong1v1pages/chooseOpponent.html
transcendence/app/templates/Pong1v1pages/twoVtwoEndGame.html

Games can now be saved in all kind of games. They are saved when the game is over, no need for user action

Saved games

---

Makefile
transcendence/api/models.py
transcendence/api/tournamentController.py
transcendence/api/userController.py
transcendence/auth.py

Stats update

---

transcendence/app/static/css/languagesDropdown.css
transcendence/app/static/css/menus.css
transcendence/app/static/css/search.css
transcendence/app/static/js/Menus.js
transcendence/app/templates/SearchElements/searchItem.html
transcendence/app/templates/menus.html

Added better accessibility for menu, specially to navigate on search bar with keyboard

Search accessibility

---

transcendence/app/static/css/languagesDropdown.css
transcendence/app/static/css/menus.css
transcendence/app/static/css/pong1v1.css
transcendence/app/static/css/pong2v2.css
transcendence/app/static/css/tournamentStart.css
transcendence/app/static/style.css
transcendence/app/templates/Pong1v1pages/splash1v1.html
transcendence/app/templates/Pong1v1pages/splash2v2.html
transcendence/app/templates/Pong1v1pages/twoVtwoBoard.html
transcendence/app/templates/Pong1v1pages/twoVtwoChooseOpponent.html
transcendence/app/templates/PongTournamentPages/LocalTournament/dashboard.html
transcendence/app/templates/PongTournamentPages/LocalTournament/scorePage.html

Fixed text overflow if player has big name

Fix text overflow

---

transcendence/app/static/css/usersPage.css
transcendence/app/templates/Pong1v1pages/twoVtwoChooseOpponent.html

users page username size fixed.
2v2 registration columns size fixed

small Fixes

---

transcendence/api/translations/dashboard.py
transcendence/api/translations/main.py
transcendence/api/translations/menus.py
transcendence/api/translations/pong.py
transcendence/api/translations/translation.py
transcendence/app/mainPage.py
transcendence/app/pongTournament.py
transcendence/app/static/js/Menus.js
transcendence/app/templates/PongTournamentPages/pong.html
transcendence/app/templates/changePictureModal.html
transcendence/app/templates/languagesDropdown.html
transcendence/app/templates/lastGames.html
transcendence/app/templates/main.html
transcendence/app/templates/menus.html
transcendence/app/templates/statsArea.html
transcendence/app/userInterface.py
transcendence/app/utils.py
transcendence/transcendence/settings.py

added a folder for the translations.
Inside there is files for translating the templates.
On utils created a function to pic the correct translations according the language.

Translations

---

Makefile
transcendence/api/tournamentController.py
transcendence/api/translations/error.py
transcendence/api/translations/translation.py
transcendence/api/userController.py
transcendence/app/forms.py

new translations for tournament and user controller

Error messages
